In [2]:
import numpy as np

In [3]:
arr=np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
random_arr=np.random.rand(3,3)
print(random_arr)

[[0.93517059 0.47956877 0.00914288]
 [0.27762345 0.86625735 0.56060028]
 [0.50512154 0.44280947 0.96877059]]


In [9]:
shp=arr.shape
size=arr.size
dt=arr.dtype
print("shape:",shp)
print("size:",size)
print("Data type:",dt)

shape: (41,)
size: 41
Data type: int64


In [10]:
new=arr+5
print(new)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [12]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[1,2,3]])
mul=a*b
print(mul)

[[ 6 14 24]
 [ 4 10 18]]


In [18]:
array= np.array([[1,2,3,4,5],[6,7,8,9,10],[ 11, 12, 13, 14, 15],[ 16, 17, 18, 19, 20],[ 21, 22, 23, 24, 25]])
print(array[0,:])

[1 2 3 4 5]


In [22]:
x = np.arange(1, 26).reshape(5, 5)
first_row = x[0, :]
last_col=x[:,-1]
sub=x[:3,:2]
print(first_row)
print(last_col)
print(sub)

[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [25]:
random_int=np.random.randint(1,100,size=10)
print("random array:",random_int)
print("max: ",random_int.max())
print("min: ",random_int.min())
print("mean: ",random_int.mean())
print("standard deviation: ",random_int.std())

random array: [76 52 63 41 85 21 74 47 14 82]
max:  85
min:  14
mean:  55.5
standard deviation:  23.66114959168299


In [26]:
arr1 = np.arange(1, 13)
reshaped = arr1.reshape(3, 4)
print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
ones=np.ones((3,3))
print(ones)
added=ones+[[1,2,3]]
print(added)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [36]:
arr_50=np.random.randint(1,51,10)
div_5=arr_50[arr_50%5==0]
print(arr_50)
print(div_5)

[11 17 20 20 13  7 33 24 33 17]
[20 20]


In [40]:
m=np.array([[1,2],[4,5]])
n=np.array([[6,7],[1,2]])
mul_mat_dot=np.dot(m,n)
print(mul_mat_dot)

[[ 8 11]
 [29 38]]


In [41]:
array_4 = np.array([[1,2,3,4],[1,5,6,2],[4,5,3,2],[8,9,0,3]])
diagonal_ele = array_4[np.diag_indices(4)]
print(diagonal_ele)


[1 5 3 3]
